baseurl = "https://ynakahashi.github.io/ForBlogs/"
relativeurls = true
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja-jp"
theme = "hugo-strata-theme"
disqusShortname = "ynakahashi"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
title = "blogdown is awesome!!"
[params]
	name = "Your name"
	description = "Describe your website"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []

   [params.sidebar]
     bio = "この素晴らしき**R**な世界"

	[params.about]
		hide  = false
		title = "About this blog"
		content = "This blog is writtne by ..."

	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = true
		title = "Get In Touch"
		content = "Accumsan"

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "39.7889055,-120.5443524"
		address = [
			"1234",
			"Tokyo",
			"Japan"
		]
		phone = "000-000-0000"
		email = "hello@example.com"

		[params.contact.form]
			name = "ynakahashi"
			email = "ynakahashi"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 0
